// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActiveChannel struct {
	ID        int32
	GuildID   string
	ChannelID string
	CreatedAt pgtype.Timestamptz
}

type Guild struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Sound struct {
	ID        int32
	Name      string
	Url       string
	CreatedAt pgtype.Timestamptz
}
