version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - db
    networks:
      - bot-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-adgmusic}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot-network

volumes:
  postgres_data:

networks:
  bot-network:
    driver: bridge 